import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { MainContent } from '../components/main/MainContent'
import { ContactForm } from '../components/form-mail/ContactForm'
import { Button } from '../components/darkbutton/Button'
import { useState } from 'react'



export default function Home() {

  const[dark,setDark] = useState(false);
  const handleClick = (e) =>{
    setDark((dark) => !dark);
    `${(e.target.checked === true)? console.log("クリック") : console.log("外れました")}`
  }


  return (
    <>
      <Head>
        <title>My Portifolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main_css} ${dark ? styles.main_css2 : styles.main_css}`} onChange={handleClick}>
        <div>
          <input type='checkbox' id='checkbox' name='checkbox'/>
          <label htmlFor='checkbox'>チェック</label>
        </div> 
        <MainContent/>
        <ContactForm/>
      </main>
    </>
  )
}
