import Link from 'next/link'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React from 'react'
import { InformationData } from '../components/information/InformationData'
import { InformationFunction } from '../components/information/InformationFunction'

export default function Information(props) {
  return (
    <>
      <Head>
        <title>Information</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main_css} ${props.dark ? styles.main_css2 : styles.main_css}`}>
      <InformationFunction Data={InformationData}/>
      </main>
    </>
  )
}

