import Head from 'next/head'
import Image from 'next/image'
import { SkillData } from '../components/skill/SkillData'
import { SkillFunction } from '../components/skill/SkillFunction'
import styles from '../styles/Home.module.css'


export default function Skill(props) {
  return (
    <>
      <Head>
        <title>Skill</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main_css} ${props.dark ? styles.main_css2 : styles.main_css}`}>
        <SkillFunction slide ={SkillData}/>
      </main>
    </>
  )
}